[project]
name = "lab6"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.118.0",
    "pydantic>=2.11.9",
    "uvicorn>=0.37.0",
]
