[project]
name = "client"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.1",
    "cryptography>=46.0.3",
    "pydantic>=2.12.3",
]
